### PR TITLE
Features/zsh notes and releases

### PR DESCRIPTION
**Pull request by EnriqueVidal**
- [x] Add basic support for zsh to keep things working for people on zsh and macs
- [x] Update README
- [ ] ~Create Github Workflow for CI~
- [ ] ~Create Github Workflow for CD~

### CODE REVIEW

**Comment by aalvarado** [comment]
what do you think about adding a bin apps repo to track any CLI apps that we might want to share? I have a date system that I've been using with `date +F`

**Comment by aalvarado** [comment]
I love these changes btw

**Comment by EnriqueVidal** [comment]
> what do you think about adding a bin apps repo to track any CLI apps that we might want to share? I have a date system that I've been using with `date +F`

How would you do it, like a bin folder with a bunch of git submodules?

**Comment by EnriqueVidal** [comment]
> I love these changes btw

I need to get back to this, something is failing to install in the github action but I can't see it so it's hard to debug

**Comment by aalvarado** [comment]
> > what do you think about adding a bin apps repo to track any CLI apps that we might want to share? I have a date system that I've been using with `date +F`
> 
> How would you do it, like a bin folder with a bunch of git submodules?

Maybe a `bintools` repo? I think we could do one under clover? or some other org

**Comment by EnriqueVidal** [comment]
> > > what do you think about adding a bin apps repo to track any CLI apps that we might want to share? I have a date system that I've been using with `date +F`
> > 
> > How would you do it, like a bin folder with a bunch of git submodules?
> 
> Maybe a `bintools` repo? I think we could do one under clover? or some other org

Yeah that sounds reasonable

**Comment by EnriqueVidal** [comment]
After thinkering with github workflows I realize that after the dotfiles are installed there's really no way of testing other than trust the installer did not fail, I decided it's not worth holding off on these updates until a testing strategy is in place so I'll handle that in a separate PR

**Pull request merged**
