### PR TITLE
Add Dropdown Quake like terminal with Scratchpad

### PR DESCRIPTION
**Pull request by aalvarado**
Add Dropdown Quake like terminal with Scratchpad using urxvt

### CODE REVIEW

**Comment by EnriqueVidal** [comment]
Looks good, will test tonight.

**Comment by EnriqueVidal** [comment]
I may be missing something but the `$mod+grave` is not briging the `urxvt` for me.

**Comment by aalvarado** [comment]
can you try this:

`i3-msg "exec --no-startup-id urxvt --title __scratch &"`

**Comment by aalvarado** [comment]
Seems this would only work with Alacritty and not other terminals. There are other ways but this one is very specific to me. Closing

**Pull request closed without merging**
