### PR TITLE
Features/i3wm

### PR DESCRIPTION
**Pull request by EnriqueVidal**
Add i3wm configuration.

### CODE REVIEW

**Comment by EnriqueVidal** [comment]
I just wasted like 4 hours trying to figure out why x wouldn't start in any session other than root, it turns out this is a problem with the virtualbox additions, [source](https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1525735/comments/3), as of now the only way to start X as any user in Virtual box is to install: `xserver-xorg-legacy` and `virtualbox-guest-dkms` this should not be the case in a real machine so there's no reason to put this in the install script, after running the installer all dependencias are installed and running xinit renders this:

screen shot 2016-05-27 at 3 57 32 pm

I'm still tweaking the config and rake task, since this was taken from my linux box a bunch of config is specific to my hardware but I should be able to come up with the bare minimum for it to work a clean setup.

The install script assumes you installed the minimal version of the OS, which has no X, or desktop environment, and install the necessary packages like xorg and i3, installation should be a lot faster in a box that already has a working X server.

**Comment by EnriqueVidal** [comment]
Should work know, a couple of notes, I added a provisional wallpaper, but we can and probably should replace it with something else:

Wallpaper

At the moment the whole desktop setup is separated from the `Rakefile`, the reason for this is that the whole thing is specific to Linux, after you run the installer in vagrant simply run xinit and the desktop will start and open up a terminal window.

### TODO

* Find a better way to get fonts other than copying from a git submodule
* Improve i3blocks config
* Write a README for i3
* Get standard config for compton, transparencies are not enabled at the moment since we're dealing with a virtual machine upon starting the box compton would crash X

Apart from the list above everything else should work simply running the installer even if the box has no X server.

**Comment by aalvarado** [comment]
I will try the setup today and see if I run into any issues

**Comment by EnriqueVidal** [comment]
Here's a preview of how rofi looks like:

screen shot 2016-06-10 at 11 35 13 am

**Comment by aalvarado** [comment]
tried to run this today but I see that I need to update my base boxes to Xenial.

**Comment by aalvarado** [comment]
I don't want this release to be held back because I'm unable to test. we should ship and wait for bugs.

**Pull request merged**
